### ISSUE TITLE
disappearing modifications

### ISSUE THREAD

**Issue by milpataki** [MicrosoftDocs/mslearn-consume-rest-based-web-services-in-xamarin-apps#11]
All my DB modifications disappear after closing the App (new, edit, and deleting books included).
Is this normal? (android)

**Comment by jamesmontemagno** [comment]
Yes, that is expected. The app doesn't save the token at all as it was it was just to keep the sample simple for the learn module.

you could however change this by saving the token you get when you login -> 
https://github.com/MicrosoftDocs/mslearn-xamarin-consume-rest-services/blob/master/src/exercise1/final/BookClient/BookClient/Data/BookManager.cs#L20

Use essentials perferences api to save it off -> https://docs.microsoft.com/xamarin/essentials/preferences

The backend service does purge auth tokens though
