### ISSUE TITLE
Obsolete API: Button.BorderRadius

### ISSUE THREAD

**Issue by randroid88** [MicrosoftDocs/mslearn-consume-rest-based-web-services-in-xamarin-apps#4]
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0618	'Button.BorderRadius' is obsolete: 'BorderRadius is obsolete as of 2.5.0. Please use CornerRadius instead.'

I saw this after updating Xamarin Essentials (1.1.0) and Xamarin Forms (v4.0.0.482894).

https://github.com/MicrosoftDocs/mslearn-xamarin-consume-rest-services/blob/f827ffa2c3949f0e70a0596e7e206f3f81557394/src/exercise1/final/BookClient/BookClient/AddEditBookPage.cs#L53

**Comment by patridge** [comment]
Thank you for pointing this out. I updated the NuGet packages and updated this property.
{Fixed in #7.}
