### ISSUE TITLE
iOS is not displaying the ToolbarItems

### ISSUE THREAD

**Issue by randroid88** [MicrosoftDocs/mslearn-consume-rest-based-web-services-in-xamarin-apps#5]
The ToolbarItems (Add New and Refresh) do not show up for iOS.

I've tried running the project on simulators (iPhone 8 iOS 12.2, iPad Air (3rd generation) iOS 12.2) and checking the MainPage in the Designer.

![Design](https://user-images.githubusercontent.com/11371505/58852650-38cb6100-864c-11e9-8a63-767acdeb7386.png)
![Simulator](https://user-images.githubusercontent.com/11371505/58852656-39fc8e00-864c-11e9-97b0-6460a6961096.png)

**Comment by patridge** [comment]
@randroid88 Are you still seeing this? There was a PR from @JesseDietrichson a while ago to fix some of these issues.
